## Config file for CNVPipe snakemake workflow

data:
    samples:    "/home/sunjh/data3/project/CNVPipe/analysis/samples.2.tsv"
    genome: "/home/sunjh/data3/refs/hg38/analysisSet/hg38.analysisSet.fa"
    refFlat:    ""

settings:
    read-depth:
        - cnvkit
        - mops
        - cnvpytor
        - freec
    
    snp-calling:
        - bcftools
        - freebayes
    
    breakpoints-detc:
        - lumpy
        - delly
    
    pathogenicity-pred:
        - toolA
        - toolB
    
    keep-intermediate:
        fastp: True

params:
    fastp:
        threads:    10
        se: ""
        pe: ""

    bwamem:
        threads:    10
        extra:  ""
        index: True
    
    cnvkit:
        threads:    8
        extra:  ""
    
    mops:
        threads:    8
        extra:  ""
    
    cnvpytor:
        threads:    8
        extra:  ""
    
    freec:
        threads:    8
        extra:  ""
    
    bcftools:
        threads: 8
        mode: "combined"
        mpileup: "--max-depth 10000"
        call: "--multiallelic-caller"
        stats: ""
        stats-plot: ""
    
    freebayes:
        extra: ""
        threads: 8
        compress-threads: 2
        chunksize: 100000
    
    fastqc:
        input:  "samples"
        extra:  ""



## Reference genome specific files
human_reference:        /home/jhsun/data/refs/hg38/analysisSet/hg38.analysisSet.fa
sequence_dict:          /home/jhsun/data/refs/hg38/analysisSet/hg38.analysisSet.fa.dict
refFlat:                /home/jhsun/data/refs/hg38/bundle/CNVKit/refFlat.txt
access:                 /home/jhsun/data/refs/hg38/bundle/CNVKit/access-excludes.hg38.analysisSet.bed

