## Config file for CNVPipe snakemake workflow

data:
    samples:    "/data/jinwf/jhsun/project/CNVPipe/analysis/samples.tsv"
    genome: "/data/jinwf/jhsun/refs/hg38/analysisSet/hg38.analysisSet.fa"
    access:    "/data/jinwf/jhsun/CNVPipe/resources/CNVKit/access-excludes.hg38.analysisSet.bed"
    delly-map: "/data/jinwf/jhsun/CNVPipe/resources/Delly/Homo_sapiens.GRCh38.dna.primary_assembly.fa.r101.s501.blacklist.gz"
    smoove-exclude: "/data/jinwf/jhsun/CNVPipe/resources/Smoove/hg38.sv_blacklist.bed"
    normal-common-cnv: "/data/jinwf/jhsun/CNVPipe/resources/dbVar/common_global_normal.bed"
    gatk-dbsnp: "/data/jinwf/jhsun/CNVPipe/resources/GATK/dbsnp_146.hg38.vcf.gz"
    gatk-hapmap: "/data/jinwf/jhsun/CNVPipe/resources/GATK/hapmap_3.3.hg38.vcf.gz"
    gatk-omni: "/data/jinwf/jhsun/CNVPipe/resources/GATK/1000G_omni2.5.hg38.vcf.gz"
    gatk-1000g: "/data/jinwf/jhsun/CNVPipe/resources/GATK/1000G_phase1.snps.high_confidence.hg38.vcf.gz"
    gatk-mills: "/home/jhsun/data3/CNVPipe/resources/GATK/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
    gatk-hg38: "/home/jhsun/data3/CNVPipe/resources/GATK/Homo_sapiens_assembly38.known_indels.vcf.gz"

settings:
    keep-intermediate:
        fastp: False
        bwamem: False
    
    bqsr: False

    gatk-snp: False

    recurrent: False

params:
    species: 'human'

    binSize:   1200
    
    fastp:
        threads:    6

    bwamem:
        threads:    26
        index: True
        platform:   "ILLUMINA"

    cnvkit:
        threads:    10

    cnvpytor:
        threads:    10
        
    mops:
        threads:    10

    delly:
        complex-mode: False
        
    freebayes:
        threads:    8

    recurrent-threshold: 5
